development:
  adapter: redis
  url: redis://redis:6379/1
  channel_prefix: teamchat_development

test:
  adapter: redis
  url: redis://redis:6379/1
  channel_prefix: teamchat_test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: teamchat_production
